---
# Handlers for plex-nvidia role

- name: Restart Docker
  systemd:
    name: docker
    state: restarted

- name: Reboot system
  reboot:
    msg: "Rebooting to load Nvidia drivers"
    reboot_timeout: 600

- name: Restart Plex
  community.docker.docker_compose:
    project_src: "{{ plex_compose_dir }}"
    state: present
    restarted: true
