apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Prowlarr"
    gethomepage.dev/description: "Indexer manager"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "prowlarr.png"
    gethomepage.dev/pod-selector: "app=prowlarr"
    gethomepage.dev/widget.type: "prowlarr"
    gethomepage.dev/widget.url: "http://prowlarr.media.svc.cluster.local:9696"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - prowlarr.kernow.io
      secretName: kernow-io-tls
  rules:
    - host: prowlarr.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 9696