---
apiVersion: v1
kind: Secret
metadata:
  name: arc-public-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  name: arc-public-charts
  type: helm
  url: ghcr.io/actions/actions-runner-controller-charts
