apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: notifiarr-api
  namespace: media
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /media/notifiarr
  managedSecretReference:
    secretName: notifiarr-api
    secretNamespace: media
    secretType: Opaque
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: radarr-credentials
  namespace: media
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /media/radarr
  managedSecretReference:
    secretName: radarr-credentials
    secretNamespace: media
    secretType: Opaque
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: sonarr-credentials
  namespace: media
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /media/sonarr
  managedSecretReference:
    secretName: sonarr-credentials
    secretNamespace: media
    secretType: Opaque
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: prowlarr-credentials
  namespace: media
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /media/prowlarr
  managedSecretReference:
    secretName: prowlarr-credentials
    secretNamespace: media
    secretType: Opaque
    creationPolicy: Owner
