apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: arc-github-token
  namespace: arc-runners
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /platform/arc
  managedSecretReference:
    secretName: arc-github-token
    secretNamespace: arc-runners
    secretType: Opaque
    creationPolicy: Owner
