apiVersion: infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflared
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /kubernetes
  managedSecretReference:
    secretName: cloudflare-tunnel-token
    secretType: Opaque
    secretNamespace: cloudflared
