apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maintainerr-cloudflare
  namespace: media
  labels:
    app: maintainerr
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: maintainerr.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maintainerr
                port:
                  number: 6246
