apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - cloudflare-api-token-secret.yaml
  - clusterissuer-letsencrypt.yaml
  - certificate-kernow-io.yaml
