apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Home Assistant"
    gethomepage.dev/description: "Home automation"
    gethomepage.dev/group: "Home Services"
    gethomepage.dev/icon: "home-assistant.png"
    gethomepage.dev/pod-selector: "app=homeassistant"
    gethomepage.dev/widget.type: "homeassistant"
    gethomepage.dev/widget.url: "http://homeassistant.apps.svc.cluster.local:8123"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_HOMEASSISTANT_API_KEY}}"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - homeassistant.kernow.io
    secretName: homeassistant-tls
  rules:
  - host: homeassistant.kernow.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 8123
