apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasmoadmin
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "TasmoAdmin"
    gethomepage.dev/description: "Tasmota device manager"
    gethomepage.dev/group: "Home Services"
    gethomepage.dev/icon: "tasmota.png"
    gethomepage.dev/pod-selector: "app=tasmoadmin"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - tasmoadmin.kernow.io
    secretName: tasmoadmin-tls
  rules:
  - host: tasmoadmin.kernow.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tasmoadmin
            port:
              number: 80
