apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Radarr"
    gethomepage.dev/description: "Movie collection manager"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "radarr.png"
    gethomepage.dev/pod-selector: "app=radarr"
    gethomepage.dev/widget.type: "radarr"
    gethomepage.dev/widget.url: "http://radarr.media.svc.cluster.local:7878"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - radarr.kernow.io
      secretName: kernow-io-tls
  rules:
    - host: radarr.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
