---
# Handlers for tamar role

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Redis
  systemd:
    name: redis-server
    state: restarted

- name: Restart Tamar
  systemd:
    name: tamar
    state: restarted
