apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "File Browser"
    gethomepage.dev/description: "Web file manager"
    gethomepage.dev/group: "Home Services"
    gethomepage.dev/icon: "filebrowser.png"
    gethomepage.dev/pod-selector: "app=filebrowser"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - files.kernow.io
    secretName: filebrowser-tls
  rules:
  - host: files.kernow.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: filebrowser
            port:
              number: 80
