apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reiverr-cloudflare
  namespace: media
  labels:
    app: reiverr
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: reiverr.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reiverr
                port:
                  number: 9494
