apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reiverr
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Reiverr"
    gethomepage.dev/description: "Media request and discovery"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "mdi-movie-search"
    gethomepage.dev/pod-selector: "app=reiverr"
    gethomepage.dev/href: "https://reiverr.kernow.io"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - reiverr.kernow.io
      secretName: kernow-io-tls
  rules:
    - host: reiverr.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reiverr
                port:
                  number: 9494
