apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "SABnzbd"
    gethomepage.dev/description: "Usenet downloader"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "sabnzbd.png"
    gethomepage.dev/pod-selector: "app=sabnzbd"
    gethomepage.dev/widget.type: "sabnzbd"
    gethomepage.dev/widget.url: "http://sabnzbd.media.svc.cluster.local:8080"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SABNZBD_API_KEY}}"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sabnzbd.kernow.io
      secretName: kernow-io-tls
  rules:
    - host: sabnzbd.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sabnzbd
                port:
                  number: 8080
