---
# Handlers for hb-worker role

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Investmentology
  systemd:
    name: investmentology
    state: restarted

- name: Restart Synapse HB
  systemd:
    name: synapse-hb
    state: restarted

- name: Restart Screens
  systemd:
    name: screens
    state: restarted

