apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infisical-operator-system

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/Infisical/infisical/main/k8-operator/kubectl/install.yaml
  - universal-auth-secret.yaml
