apiVersion: openebs.io/v1beta3
kind: DiskPool
metadata:
  name: talos-worker-01-pool
  namespace: mayastor
spec:
  node: talos-worker-01
  disks:
    - /dev/disk/by-path/pci-0000:00:05.0-scsi-0:0:0:1
