apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mayastor

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/openebs/mayastor-extensions/v2.5.0/deploy/operator-rbac.yaml
  - https://raw.githubusercontent.com/openebs/mayastor-extensions/v2.5.0/deploy/mayastor-daemonset.yaml
  - diskpool-worker-01.yaml
  - diskpool-worker-02.yaml
  - diskpool-worker-03.yaml
  - storageclass.yaml
