apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mayastor

resources:
  - diskpool-worker-01.yaml
  - diskpool-worker-02.yaml
  - diskpool-worker-03.yaml
  - storageclass.yaml
