apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-3-replica
provisioner: io.openebs.csi-mayastor
parameters:
  repl: "3"
  protocol: "nvmf"
  ioTimeout: "60"
allowVolumeExpansion: true
volumeBindingMode: Immediate
