apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/description: "GitOps continuous delivery"
    gethomepage.dev/group: "Platform Services"
    gethomepage.dev/icon: "si-argo"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=argocd-server"
    gethomepage.dev/widget.type: "argocd"
    gethomepage.dev/widget.url: "https://argocd.kernow.io"
    gethomepage.dev/widget.username: "admin"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_ARGOCD_PASSWORD}}"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - argocd.kernow.io
      secretName: argocd-tls
  rules:
    - host: argocd.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80