apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
  namespace: infisical-operator-system
type: Opaque
stringData:
  # Infisical Universal Auth credentials from terraform.tfvars
  clientId: "prod_homelab"
  clientSecret: "st.a46273f4-351c-4f5e-8de3-1e5f40391ffe.31920c113fa1e30fe99d6600ce7d77f5.15ecd6e9e8a199249b850c5b14e809df"
