apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - resources/ingress.yaml
  - resources/argocd-cm.yaml
  - resources/argocd-rbac-cm.yaml
  - cloudflare-tunnel-ingress.yaml

patches:
  - path: argocd-server-service-patch.yaml
    target:
      kind: Service
      name: argocd-server