apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huntarr-cloudflare
  namespace: media
  labels:
    app: huntarr
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: huntarr.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: huntarr
                port:
                  number: 9705
