apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        fsGroup: 3000
      initContainers:
        - name: copy-config
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              cp -rL /tmp/config/* /app/config/ && \
              chmod -R 755 /app/config && \
              chown -R 3000:3000 /app/config
          volumeMounts:
            - name: homepage-config-source
              mountPath: /tmp/config
            - name: homepage-config
              mountPath: /app/config
          securityContext:
            runAsUser: 0
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.kernow.io"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: HOMEPAGE_VAR_RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-radarr
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-sonarr
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_OVERSEERR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-overseerr
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_PROWLARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-prowlarr
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_SABNZBD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-sabnzbd
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_TAUTULLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-tautulli
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_TRANSMISSION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homepage-transmission
                  key: PASSWORD
                  optional: true
            - name: HOMEPAGE_VAR_HOMEASSISTANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-homeassistant
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_OPNSENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-opnsense
                  key: key
                  optional: true
            - name: HOMEPAGE_VAR_OPNSENSE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: homepage-opnsense
                  key: secret
                  optional: true
            - name: HOMEPAGE_VAR_ADGUARD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: homepage-adguard
                  key: username
                  optional: true
            - name: HOMEPAGE_VAR_ADGUARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homepage-adguard
                  key: password
                  optional: true
            - name: HOMEPAGE_VAR_UNIFI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-unifi
                  key: UNIFI_API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_TRUENAS_MEDIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-truenas-media
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_TRUENAS_HDD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-truenas-hdd
                  key: API_KEY
                  optional: true
            - name: HOMEPAGE_VAR_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: homepage-proxmox
                  key: TOKEN_ID
            - name: HOMEPAGE_VAR_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homepage-proxmox
                  key: API_TOKEN
            - name: HOMEPAGE_VAR_CARRICK_USER
              valueFrom:
                secretKeyRef:
                  name: homepage-proxmox-carrick
                  key: user
                  optional: true
            - name: HOMEPAGE_VAR_CARRICK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homepage-proxmox-carrick
                  key: token
                  optional: true
            - name: HOMEPAGE_VAR_GRAFANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homepage-grafana
                  key: key
                  optional: true
            - name: HOMEPAGE_VAR_ARGOCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homepage-argocd
                  key: password
                  optional: true
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
            - name: plexopathy
              mountPath: /mnt/plexopathy
              readOnly: true
            - name: tarriance
              mountPath: /mnt/tarriance
              readOnly: true
          securityContext:
            runAsUser: 3000
            runAsGroup: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: homepage-config-source
          configMap:
            name: homepage
        - name: homepage-config
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: plexopathy
          nfs:
            server: 10.40.0.10
            path: /mnt/Tongariro/Plexopathy
        - name: tarriance
          nfs:
            server: 10.40.0.10
            path: /mnt/Taranaki/Tarriance
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
