apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recomendarr-cloudflare
  namespace: media
  labels:
    app: recomendarr
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: recomendarr.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recomendarr
                port:
                  number: 3000
