apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: renovate
            image: renovate/renovate:42.39.2
            env:
            - name: RENOVATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: renovate-credentials
                  key: GITHUB_TOKEN
            - name: RENOVATE_PLATFORM
              value: "github"
            - name: RENOVATE_AUTODISCOVER
              value: "false"
            - name: RENOVATE_REPOSITORIES
              value: "charlieshreck/prod_homelab"
            - name: RENOVATE_GIT_AUTHOR
              value: "Renovate Bot <bot@renovateapp.com>"
            - name: LOG_LEVEL
              value: "info"
            - name: RENOVATE_ONBOARDING
              value: "false"
            - name: RENOVATE_REQUIRE_CONFIG
              value: "required"
            - name: RENOVATE_BASE_BRANCHES
              value: "main"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 1Gi
