apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: renovate-credentials
  namespace: renovate
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /infrastructure
  managedSecretReference:
    secretName: renovate-credentials
    secretNamespace: renovate
    secretType: Opaque
    creationPolicy: Owner
