apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: transmission-credentials
  namespace: media
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /media
  managedSecretReference:
    secretName: transmission-credentials
    secretNamespace: media
    secretType: Opaque
    creationPolicy: Orphan
  secretMapping:
    - secretName: TRANSMISSION_USER
      key: username
    - secretName: TRANSMISSION_PASS
      key: password
