apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: transmission-credentials
  namespace: media
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: prod-homelab-y-nij
        envSlug: prod
        secretsPath: /media/transmission
  managedSecretReference:
    secretName: transmission-credentials
    secretNamespace: media
    secretType: Opaque
    creationPolicy: Owner
