apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Transmission"
    gethomepage.dev/description: "Torrent client"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "transmission.png"
    gethomepage.dev/pod-selector: "app=transmission"
    gethomepage.dev/widget.type: "transmission"
    gethomepage.dev/widget.url: "http://transmission.media.svc.cluster.local:9091"
    gethomepage.dev/widget.username: "admin"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_TRANSMISSION_PASSWORD}}"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - transmission.kernow.io
      secretName: kernow-io-tls
  rules:
    - host: transmission.kernow.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: 9091